version: '3.8'
services:
  beanstalkd:
    image: tovifit/beanstalkd	
    ports:
      - "11300:11300"
 
  postgres:
    image: postgres:14.2-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"

    restart: always

  wape-api:
    build:
      context: ./api
      dockerfile: Dockerfile
    environment:
      PORT: 8000
      BUCKET_NAME: wape
      BUCKET_RAW: 
      BUCKET_TOKEN: 
      QUEUE_ADDR: beanstalkd
      QUEUE_PORT: 11300
      QUEUE_NETWORK: tcp
    ports:
      - "8000:8000"
    

  wape-parser:
    build:
      context: ./parser
      dockerfile: Dockerfile
    environment:
      DB_HOST: postgres
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: postgres
      DB_PORT: 5432
      QUEUE_ADDR: beanstalkd
      QUEUE_PORT: 11300
      QUEUE_NETWORK: tcp  
    ports:
      - "8001:8001"
    depends_on:
      - postgres