version: '3.8'
services:
  beanstalkd:
    image: tovifit/beanstalkd	
    ports:
      - "11300:11300"
 
  postgres:
    image: postgres:14.2-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"

    restart: always

  wape-api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    

  wape-parser:
    build:
      context: ./parser
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    depends_on:
      - postgres